import '/imports/api/users/user-methods'
import '/imports/api/events/event-methods'
import '/imports/api/cities/city-methods'
import '/imports/api/events/server/publications'
import '/imports/api/users/server/social-config'
import '/imports/api/rest/rest-routes'