import '/imports/collections/users/user-methods'
import '/imports/collections/events/event-methods'
import '/imports/collections/cities/city-methods'
import '/imports/collections/events/server/publications'
import '/imports/collections/users/server/social-config'
import '/imports/rest/rest-routes'